### ISSUE TITLE
Small typo in bulleted 'Key Vocab' section

### ISSUE THREAD

**Issue by jacoblogan98** [learn-co-curriculum/python-p4-intro-to-full-stack-development#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/pages/intro-to-full-stack-development?module_item_id=483949

### Concern

For the TCP bullet : "A connection is formed and **stars** active until the applications on either end have finished sending data to one another. "

I think this is supposed to be 'stays' instead of 'stars'.

**Comment by pgill97** [comment]
Changed starts to stays.
